# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  imageRegistry: 'IMH Demo ACR'
  containerService: 'imhdemoapp'
  serviceURL: 'mhdemoacr.azurecr.io'
  registryName: 'pipelines-javascript-docker'
  tag: '4.0'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile
    containerRegistry: $(imageRegistry)
    tags: |
      3.0
## Add the below snippet at the end of your pipeline
- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy'
  inputs:
    azureSubscription: $(imageRegistry)
    appName: $(containerService)
    containers: '$(serviceURL)/$(registryName):$(tag)'
   

